Feature/ch4519-22/sdk updates for dashboard2
workos-inc/workos-go pull request #63
Opened 2021-01-06 21:31 UTC by loferris

This feature branch reflects the following changes: adding client_id and adding deprecation warnings for project_id in sso; adding environment_id and removing project_id in audit trail and directory sync.

It has the combined content of 
ch4519
ch4520
ch4521
ch4522 
tickets on Clubhouse!

2021-01-06 21:44 UTC, loferris commented
I'm currently fixing semaphore errors.

2021-01-06 22:47 UTC, rjvani requested changes

2021-01-06 22:47 UTC, rjvani commented on pkg/directorysync/client_test.go
> -						ProjectID:   "project_id",
Should this be replaced with `EnvironmentID`?

2021-01-06 22:47 UTC, rjvani commented on pkg/directorysync/directorysync_test.go
> -				ProjectID:   "project_id",
Same comment, should we use `EnvironmentID`?

2021-01-06 22:47 UTC, rjvani commented on pkg/sso/client.go
> +	// Either ProjectID or ClientID is REQUIRED while we deprecate ProjectID..
Nit: extra period.

2021-01-06 22:47 UTC, rjvani commented on pkg/sso/sso.go
> +func Configure(apiKey, projectID string, clientID string) {
Should we just rename `projectID` to `clientID` here? Since these aren't explicitly used by developers, we can get away with a replace.

2021-01-06 22:47 UTC, rjvani commented on pkg/sso/client_test.go
> +			ID:             "client_123",
Nit: I think it's originally a typo in the old test. Since this is a profile, maybe we should do `profile_123`.

2021-01-06 22:47 UTC, rjvani commented on pkg/sso/sso_test.go
> +		ID:             "client_123",
Nit: Same comment, I think we should fix this typo and just use `profile_123`.

2021-01-07 06:18 UTC, rjvani approved these changes

2021-01-07 17:25 UTC, merged